# Generated by Django 3.0.7 on 2022-02-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams'},
        ),
    ]
