# Generated by Django 3.0.7 on 2022-02-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220206_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
